### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by DivjotRulez** [macedonga/beunblurred#10]
When trying to use https://www.beunblurred.co/ it doesn’t work I checked network and it seems to error with internal server error 500

**Comment by macedonga** [comment]
It works for me. Maybe try again?
Also https://github.com/macedonga/beunblurred/issues/9#issuecomment-1751979412

**Comment by DivjotRulez** [comment]
It seems that if you logout of beunblurred and try sign in the issue occurs
tried with multiple phone numbers still the same
