### ISSUE TITLE
Some phone numbers from specific countries can't login

### ISSUE THREAD

**Issue by Mfb9909** [macedonga/beunblurred#13]
![image](https://github.com/macedonga/beunblurred/assets/132620762/25ec3d16-f7a5-4112-8039-4bfc256e8856)
Doesn't stop loading

**Comment by macedonga** [comment]
Some phone numbers for some reason are not supported. I don't know what is the cause

**Comment by Mfb9909** [comment]
![image](https://github.com/macedonga/beunblurred/assets/132620762/95ccb6d0-b829-4de3-9413-2b4e6f1a911e)
I get this problem now that i've changed the ports

**Comment by hellololothere** [comment]
Had the same problem with it endlessly being stuck on "loading". Now it shows error 500 since you changed it. Worked perfectly fine before the new bereal update tho

**Comment by Mfb9909** [comment]
pls update

**Comment by Mfb9909** [comment]
Any fixes for this ?

**Comment by fifiballer60** [comment]
I logged out and now I cant log in again and it shows error 500 is there any reason why?

**Comment by macedonga** [comment]
Should be finally fixed!
