### ISSUE TITLE
Install issue 

### ISSUE THREAD

**Issue by Mfb9909** [macedonga/beunblurred#14]
up to date, audited 523 packages in 2s

90 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (1 low, 3 moderate, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by Mfb9909** [comment]
![image](https://github.com/macedonga/beunblurred/assets/132620762/8c1ba4d1-245c-417f-8166-7f0b7c1bfc07)

**Comment by macedonga** [comment]
There's a server running on the port 3290. Try rebooting your pc or finding out what process is listening on that port and kill it.

**Comment by Mfb9909** [comment]
Ok, if I can't find what's running on that port can I change the specified port?

**Comment by macedonga** [comment]
Yes, just edit the package.json file with the port you want

**Comment by Mfb9909** [comment]
Doesn't work for me
