### ISSUE TITLE
new bereal update

### ISSUE THREAD

**Issue by 083noah** [macedonga/beunblurred#16]
can you update it please, to make it work again? would be great!

**Comment by macedonga** [comment]
I'm going to have to check out what's wrong since it returns 403 forbidden. I thought they might have IP banned the server but it wasn't the case.

**Comment by 083noah** [comment]
> I'm going to have to check out what's wrong since it returns 403 forbidden. I thought they might have IP banned the server but it wasn't the case.

okay, thank you very much! would be very nice if you could do it today (if you have time) cause I have to see today's bereal really. I think it will leave around 7pm 

thanks  :)

**Comment by 083noah** [comment]
> I'm going to have to check out what's wrong since it returns 403 forbidden. I thought they might have IP banned the server but it wasn't the case.

Console log (browser dev tools) shows a error:

Failed to load resource: the server responded with a status of 403 (Forbidden)
CORS Anywhere. URL http://localhost:8080/https://mobile.bereal.com/api/feeds/friends-v1

Response:
Missing required request header. Must specify one of: origin,x-requested-with

**Comment by mynameisnitro** [comment]
Another repo succeded in solving the issue, so I think we may need to copy requests infos: https://github.com/rvaidun/befake

**Comment by macedonga** [comment]
I'll check it out this afternoon

**Comment by mynameisnitro** [comment]
Here's what to change:

pages/api/fire/verify.js
``const reqOptions = {
            headers: {
                Authorization: `Bearer ${access_token}`,
                'bereal-app-version-code': '14549',
                'bereal-signature': 'berealsignature',
                'bereal-device-id': 'berealdeviceid',
            }
        }``

pages/api/discovery.js
``feedResponse = await axios.get(
            "https://mobile.bereal.com/api/feeds/discovery?limit=100",
            {
                "headers": {
                    "Authorization": `Bearer ${data.token}`,
                    'bereal-app-version-code': '14549',
                    'bereal-signature': 'berealsignature',
                    'bereal-device-id': 'berealdeviceid',
                }
            }
        );``

pages/api/fof.js
``feedResponse = await axios.get(
            "https://mobile.bereal.com/api/feeds/friends-of-friends" + (nextToken ? ("?page=" + nextToken) : ""),
            {
                "headers": {
                    "Authorization": `Bearer ${data.token}`,
                    'bereal-app-version-code': '14549',
                    'bereal-signature': 'berealsignature',
                    'bereal-device-id': 'berealdeviceid',
                }
            }
        );``

pages/u/[id].js
``const reqOptions = {
        headers: {
            Authorization: `Bearer ${token}`,
            'bereal-app-version-code': '14549',
            'bereal-signature': 'berealsignature',
            'bereal-device-id': 'berealdeviceid',
        }
    };``

pages/feed.js
``const reqOptions = {
        headers: {
            Authorization: `Bearer ${token}`,
            'bereal-app-version-code': '14549',
            'bereal-signature': 'berealsignature',
            'bereal-device-id': 'berealdeviceid',
        }
    };``

p

**Comment by macedonga** [comment]
Thanks @mynameisnitro!

Everything should be working now :-)
