### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Mfb9909** [macedonga/beunblurred#18]
![image](https://github.com/macedonga/beunblurred/assets/132620762/70ac443d-f88a-4141-9d89-20131c08073a)

**Comment by macedonga** [comment]
Duplicate of #13. This is the reason it's not working with some phone numbers. I don't know the cause yet.

**Comment by Mfb9909** [comment]
Ah I see, thanks for the update

**Comment by Mfb9909** [comment]
Any fixes?
