### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by 083noah** [macedonga/beunblurred#19]
Feed is not loading because of Error 5000

**Comment by mynameisnitro** [comment]
Looks like BeReal updated their /friends-v1 api since we get 401 Unauthorized code

**Comment by 11prasicc11** [comment]
please update bro 💯

**Comment by Ein-Tim** [comment]
More details can be found in https://github.com/rvaidun/befake/issues/199#issuecomment-1935853837

**Comment by macedonga** [comment]
Should be fixed.
