### ISSUE TITLE
Returns a Server Error

### ISSUE THREAD

**Issue by Breathix** [macedonga/beunblurred#2]
Hello, when trying to log in to my BeReal account after entering the sms verification it gives me this error :

[image](https://github.com/macedonga/beunblurred/assets/103904922/55e69f8b-47f9-4ae5-9026-da94bb29de1d)

**Comment by macedonga** [comment]
Hey,
Everything should work now. The error was caused by a commit i made yesterday.

Please tell me if it works so I can close this issue.

**Comment by macedonga** [comment]
I'm closing this issue.
