### ISSUE TITLE
is there something new?

### ISSUE THREAD

**Issue by 083noah** [macedonga/beunblurred#21]
do you think you can fix it?

**Comment by Ein-Tim** [comment]
@macedonga There are new infos, see https://github.com/rvaidun/befake/commit/e54e0ec424d44d56375395e9b4dd3b39ee72c250. So BeUnblurred can be fixed.

**Comment by macedonga** [comment]
> @macedonga There are new infos, see [rvaidun/befake@e54e0ec](https://github.com/rvaidun/befake/commit/e54e0ec424d44d56375395e9b4dd3b39ee72c250). So BeUnblurred can be fixed.

Just implemented it. Thanks :-)
