### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by 11prasicc11** [macedonga/beunblurred#23]
can you help me, the option to download bts videos no longer exists

**Comment by macedonga** [comment]
I never removed the option to download BTS videos from posts. Are you sure you're clicking the options menu of the post with the BTS video?

**Comment by 11prasicc11** [comment]
check, the option has disappeared since maybe two or three days ago

**Comment by macedonga** [comment]
Oh, I see what you mean... Just fixed it. Thanks!
