### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 11prasicc11** [macedonga/beunblurred#24]
shit, it's broken again 😵‍💫

**Comment by macedonga** [comment]
Yeah, BeReal probably changed something again... I'll have to check it out, but for now login seems to work fine, it's just the feed endpoint not working.

**Comment by 11prasicc11** [comment]
thank you bro, I hope it's not something serious and that you can solve it 🤗

**Comment by macedonga** [comment]
Fixed with latest commit.
