### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by 11prasicc11** [macedonga/beunblurred#25]
bro, in which part did the change occur, can i fix the "befakes" myself, since the dev is not responding, and i need that project too

**Comment by macedonga** [comment]
Change all the "bereal-signature" headers to this value: "MToxNzEwOTU0MTc2OmPlM3WPWqPWRq7EseRiT98fErcmwWg1yUatGmYZnzaH"

**Comment by 11prasicc11** [comment]
bro, you are the doctor for this ❤️, can I contact you privately for some other things I am interested in, if somehow possible

**Comment by macedonga** [comment]
Sure, you can see all the ways you can contact me at https://marco.win/contact
