### ISSUE TITLE
Constant 500 errors and problems with some URLs

### ISSUE THREAD

**Issue by Gburmester** [macedonga/beunblurred#27]
Hello,

At the moment I have two problems with beunblurred:

1) The first problem was introduced when generating the new signatures. Now it mostly always shows the 500 error when I load the feed page (I have a bookmark on that page) and I have to reload to see the posts

2) The second problem first surfaced after the big fix in early February and continues until this day: Sometimes the main or secondary picture is not shown and it only generates a 39 byte file with this content: {"error":"Invalid URL","success":false}
This picture is then not accessible by any means with beunblurred, it is also not shown when logging in as another user which is also friended with the user that has the picture. As beunblurred shows only blobs I can't say which URL is the problem. Is there some debug switch to output all URLs?

Thanks for looking into this problems and also thanks for your great work!

**Comment by GWPvGWP** [comment]
I experience the same issues.

Regarding the second issue:
-the image is accessible when you copy the image link via the button menu and paste that link in your browser for example
-I noticed now there are many variants used in the urls: not only cdn.*bereallink/userID/photoID* but also cdn-xxx.*bereallink/userID/photoID*. Maybe that causes the issue in some cases?

Maybe it would be nice to have a button to copy all URLs at once. In case you have no time to check all bereals but you would like to see them later, that would be an option to store access to the images without having to download them all. Ideally, you would automate this to do this every day just a minute before the new bereal moment is pushed. If we only knew that moment ;)

**Comment by macedonga** [comment]
The 500 errors should be fixed! I made a really dumb mistake on the code that makes the request after refreshing the authentication token... 

Also, I just changed the regex for checking if the image url is a valid one. Could you check if it works now?
If you still have that problem you could use the Network tab on the devtools and check the requests that start with `https://www.beunblurred.co/api/cors/?endpoint=` to get the URL that is causing problems.
I'm using [this](https://github.com/macedonga/beunblurred/blob/main/pages/api/cors.js#L13) regular expression to check if the url of the provided image is a bereal cdn link.

**Comment by macedonga** [comment]
> Maybe it would be nice to have a button to copy all URLs at once. In case you have no time to check all bereals but you would like to see them later, that would be an option to store access to the images without having to download them all. Ideally, you would automate this to do this every day just a minute before the new bereal moment is pushed. If we only knew that moment ;)

It would be a nice feature! Maybe I could write a standalone program to run on your PC so that bereals are automatically archived! I'll put this on my TODO list :-)

**Comment by macedonga** [comment]
Alright, I discovered some BeReal introduced a *new* *new* cdn url, something like cdn-mc-eu1-fd5f74b2.bereal.network, so I fixed the regex to work with that url too. Should be fixed :-)

**Comment by GWPvGWP** [comment]
Well done, now it runs smooth again :)
