### ISSUE TITLE
vercel deployment

### ISSUE THREAD

**Issue by s-alad** [macedonga/beunblurred#29]
Nice project 😉 Was wondering if it's hosted on Vercel - seems like it? If so was wondering how your cloud functions weren't getting blocked by bereal due to the vercel header

**Comment by macedonga** [comment]
Sorry, I'm not hosting it on Vercel. I used to do that on the first weeks, but then noticed that some requests started getting blocked, so I just moved to a VPS. Thinking about it now I could've made a proxy server to bypass those blocked requests, but i think it's just easier to move it to a VPS. Also, I love your client! :-)
