### ISSUE TITLE
Friends of Friends feed error

### ISSUE THREAD

**Issue by GWPvGWP** [macedonga/beunblurred#3]
Hi Marco,

your client is super cool, I really like it! But I fear the Friends of Friends feed already broke, or is it just me?

**Comment by macedonga** [comment]
Hey,
it looks like the `https://mobile.bereal.com/api/feeds/friends-of-friends` endpoint is always returning `{ data: [] }` for some reason. Probably BeReal changed the endpoint.
Give me a few hours and it might be fixed :-)

**Comment by macedonga** [comment]
I think BeReal might have made the API not return any post if you don't have a shared BeReal.
I tried with an account that posted a BeReal and it returned the posts, while an account that didn't post anything got the empty answer.

**Comment by macedonga** [comment]
Yeah, BeReal blocked the endpoint for users who haven't posted a public BeReal.
This is the page when you have posted a public BeReal: ![image](https://i.marco.win/chrome_6w5ruwODQo.png)
And this is the page when I deleted the BeReal that was posted: ![image](https://i.marco.win/chrome_a9C4UtY5S8.png)

Sorry, but there's nothing I can do about it :-(
I'll just add a warning on the page to tell users about this

**Comment by GWPvGWP** [comment]
Well, that's sad. The joy was short. I think they have seen your work too ;)

Thanks though!
