### ISSUE TITLE
Order of posts (again?)

### ISSUE THREAD

**Issue by GWPvGWP** [macedonga/beunblurred#32]
Thanks for the recent improvements, Marco! It's still getting better and better.
I feel like something is going wrong though with the order of posts with bonus bereals I guess. It might be like what happened earlier, the post doesn't come to the top after a bonus bereal is posted.
Could you check it out?

Optional features in case you have nothing to do:
-support for tags of other uses (now it is only mentioned if it is a repost of someone)
-mention when a post contains a photo from storage (it seems this is a new feature in the bereal app)

**Comment by macedonga** [comment]
Hmmmm that's weird, I'll check it out... Would you mind maybe showing me what it looks like, since for me it's all working fine. (you can send a screen record in private via Discord if you want, my username is macedonga there too)

**Comment by GWPvGWP** [comment]
It is only in the app I see now. In the chrome browser it works fine.
Also, in the app I see the not-affiliated-warning, not in the browser. That
could be on purpose idk.

Op wo 1 mei 2024 11:55 schreef Marco Ceccon ***@***.***>:

**Comment by macedonga** [comment]
> It is only in the app I see now. In the chrome browser it works fine.

Hmmm, that's weird... Maybe try reinstalling the app? It could be a cache issue.

> Also, in the app I see the not-affiliated-warning, not in the browser. That could be on purpose idk.

That is on purpose :-)

**Comment by GWPvGWP** [comment]
OK, it's not platform specific. Only occasionally it displays correctly, it needs a few refreshes. I will keep monitoring it and maybe reinstalling.

**Comment by macedonga** [comment]
> OK, it's not platform specific. Only occasionally it displays correctly, it needs a few refreshes. I will keep monitoring it and maybe reinstalling.

Alright, so I'll close the issue for now, and if you find anything new feel free to reopen this.

**Comment by macedonga** [comment]
Forgot to tell you here, but I found out what was wrong, and fixed it :-)
