### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by blueskyy24** [macedonga/beunblurred#37]
After logging in, the feed isn‘t loading. It says „ Internal server error
Looks like something went wrong on the server side. This usually means that your token cookie has expired, and it couldn't be refreshed. Try reloading this tab, or if that doesn't work, logging out and logging back in.“ 
Reloading the page and logging in again doesn‘t fix it.

**Comment by macedonga** [comment]
From what country is the number you're using to login?

**Comment by Professoroink167** [comment]
When I logged in, it says that the international servers are down .🤔

**Comment by macedonga** [comment]
> When I logged in, it says that the international servers are down .🤔

Can you send a screenshot?

**Comment by Professoroink167** [comment]
![Screenshot_20240723_130540_Chrome](https://github.com/user-attachments/assets/8ec7d78c-9b0a-4c32-9066-a0e86e4d1249)

**Comment by blueskyy24** [comment]
I have a german number. The error looks like Professoroink167’s screenshot.

**Comment by macedonga** [comment]
This is weird, I tried with a german number and it seems like everything is working just fine for me, so the country is not the problem here...

![image](https://github.com/user-attachments/assets/e0cbf511-979a-48c0-bb3c-49196b95155d)

**Comment by blueskyy24** [comment]
I can still see my friends and their pinned Bereals, but the main feed is not loading, as shown in the screenshot.

**Comment by Professoroink167** [comment]
Same

**Comment by Professoroink167** [comment]
Now its all black when i start it
