### ISSUE TITLE
Couldn't load this image.
BeReal is probably having some issues.

### ISSUE THREAD

**Issue by oleksa4262** [macedonga/beunblurred#40]

**Comment by oleksa4262** [comment]
90% of photos aren't loaded, I've had this issue for the past 6 hours. Tried different browsers and pc version, it's still there. Bereal is not down

**Comment by DasKekse73** [comment]
same issue for me, but when you Copy the links of the Images to the Clipboard (with the little menu on the top right Corner in every bereal) and paste the links in a new Tab you can still See the Images
