### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by hellololothere** [macedonga/beunblurred#5]
Option to save is gone. Only shows option: show, send and copy

**Comment by macedonga** [comment]
What browser are you using?

**Comment by macedonga** [comment]
I've added a menu to download the BeReal.
![](https://i.marco.win/chrome_KVnOJ7t02J.png)
It lets you download the images you want, or even download the images "combined".
![](https://i.marco.win/chrome_JYGYnQQEsG.png)
