### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by JoLukas** [macedonga/beunblurred#54]
Hey, I've subscribed to BeUnblurred. But since then I keep getting the message Error (500) when I try to log in with my phone number.

**Comment by blueskyy24** [comment]
I‘m not a subscriber but same issue for me using a german number. Login seems to be not working since begin of the week.

**Comment by macedonga** [comment]
Managed to fix it for good now! Sorry for the trouble... I'll give every subscriber 50% off for a month to apologize. You probably should login and update the archiver's saved credentials, so that it can start archiving again

**Comment by JoLukas** [comment]
Again the Error 500 for German numbers🥺
