### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by starwarsman981** [macedonga/beunblurred#56]
Error 500 again when attempting to OTP. Also coupled with the absolutely INSANE verification method...

**Comment by tt-s8** [comment]
Me too.(I tried it with a Japanese phone number.) And Recaptcha is hard to solve.

**Comment by macedonga** [comment]
I think i know what the issue is: the server is making to many login requests
BeUnblurred works locally... So I'll implement proxies in the next few hours :-)

**Comment by macedonga** [comment]
also, i can't do anything about the captcha :-(

**Comment by sveaalessxa** [comment]
> Error 500 again when attempting to OTP. Also coupled with the absolutely INSANE verification method...

me too

**Comment by macedonga** [comment]
I implemented proxies, but it still doesn't work on production. I tried on the server to run it in development mode (not on the beunblurred.co domain) and it works. So my guess is that:
1 - the captcha doesn't work on the beunblurred.co domain, but it does on localhost and ip addresses
2 - there is something going wrong when building the app (maybe sentry?)

**Comment by tt-s8** [comment]
It is running in local. Thank you.

**Comment by reuddery** [comment]
be unblurred still doesn't work

**Comment by reuddery** [comment]
beunblurred still doesn't work

**Comment by macedonga** [comment]
Should be fixed now!

**Comment by VCerceau** [comment]
Still has error type 500 for me (🇫🇷 +33 numero)
