### ISSUE TITLE
Can only see last 10 posts

### ISSUE THREAD

**Issue by starwarsman981** [macedonga/beunblurred#57]
Website still not working so this is running locally.

For example, it says 54 friends have posted, but I can only see the last 10 posts. Currently I see 45-54
Earlier it was 10 posts, and now that more have posted, it's a different 10 posts, maybe 33-42

Everything is working functionally for the 10 posts i can see,

**Comment by tt-s8** [comment]
I'm having this happen too.

**Comment by starwarsman981** [comment]
How far did you go back? 

> @macedonga I can confirm that. This happens using the latest version locally and also on beunblurred.co: It says 13 users posted and I can only see the posts of 10 users. As workaround you can use the current version to get you a valid token and then use some older version locally to get the missing posts.

**Comment by svenborgmann** [comment]
> How far did you go back?

I use a old May 02 code with only the sig-token (Sep 03) changed but I think anything older than last week should work

**Comment by macedonga** [comment]
Should be fixed now, sorry!
