### ISSUE TITLE
Ability to post a BeReal

### ISSUE THREAD

**Issue by Maaaxeuh** [macedonga/beunblurred#58]
**Is your feature request related to a problem? Please describe.**
Posting a "fake" BeReal

**Describe the solution you'd like**
Be able to post a BeReal with:
- custom images (back/front)
- custom music
- custom time
- custom location
- etc

**Describe alternatives you've considered**
There is another project called [FH-DEV1/BeFake](https://github.com/FH-DEV1/BeFake) who do the same thing, but I think it would be cool on BeUnblurred too.

**Additional context**
See https://befake.website (when auth is working lol)

**Comment by macedonga** [comment]
No, sorry, that goes against BeReal terms of service, so it won't be implemented :-/
