### ISSUE TITLE
Can someone help me with this issue, when im running locally?

### ISSUE THREAD

**Issue by Heylook1** [macedonga/beunblurred#59]
![Screenshot](https://github.com/user-attachments/assets/5f931b43-7eef-4dc1-8812-4fdc771ae81f)

When im trying to run the project locally, I keep getting this error. Can someone help?
Thanks!

**Comment by retoheusser** [comment]
The readme states that you should disable the archiver in your local config, maybe that's your issue?
https://github.com/macedonga/beunblurred/blob/main/README.md

**Comment by macedonga** [comment]
That's weird, did you follow the instructions on the readme like @retoheusser said?

**Comment by Heylook1** [comment]
I actually dont know what an archiver is and also not how to disable it. Haha, I'm sorry :D

**Comment by GWPvGWP** [comment]
It is step 3 in the readme. I got a comparable error before I found out the name of the file name you need to add was incorrect.

**Comment by Heylook1** [comment]
Ok. What should I name it?

**Comment by GWPvGWP** [comment]
> Create a **.env.local** file with the following content:
NEXT_PUBLIC_NO_ARCHIVER=1

**Comment by Heylook1** [comment]
Ok, I already did that. I put it directly into the beunblurred folder, is that correct?

**Comment by GWPvGWP** [comment]
Should work yes
My mistake was that I forgot to remove the extension suffix ".txt", since I made the file as a notepad file

**Comment by Heylook1** [comment]
Unfortunately it still does not work for me

**Comment by macedonga** [comment]
> Unfortunately it still does not work for me

Are you sure you have named the file `.env.local` and not `.env.local.txt`? ([you should enable the "Show file extensions" option on windows explorer](https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/))

**Comment by Heylook1** [comment]
My fault. Thanks for your time. It works locally now. :D
