### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by GWPvGWP** [macedonga/beunblurred#6]
Hi,

as a frequent user I encounter the error 500 quite often. Sometimes refreshing works, but after some time I need to log out and log in again. I think it happens every few day or at least weekly. Are you aware of this problem or do you you think this can be solved?

Thanks for your service anyways ;)

**Comment by macedonga** [comment]
Yeah, I think it's beause BeReal had multiple outages in Europe, and since the servers hosting BeUnblurred.co are located in Europe, so consequently BeUnblurred is affected.
