### ISSUE TITLE
Display problems/Jumping after downloading primary/secondary/accessing the menu

### ISSUE THREAD

**Issue by svenborgmann** [macedonga/beunblurred#60]
**Describe the bug**
When accessing the menu it sometimes happens to jump to the beginning or the end of the list.

**To Reproduce**
1. Go to the menu of some friend in the middle of the list, f.e. you have 20 friends go to the 10th. 
2. Sometimes you can see the list in the background jumps to the first friend or the last friend, don't know how that is decided.

**Expected behavior**
It should not jump to another friend, it should stay at that friend so I can continue scrolling down to the next.

**Desktop (please complete the following information):**
 - OS: Linux Fedora
 - Browser Firefox
 - Version 131.0.3

It was fine in the May 02 code but lately I use the current code more often where I can see that behavior. It was so on the online version at around August, maybe earlier.

**Comment by svenborgmann** [comment]
I can do that when I am at that specific machine. I really thought this is a common problem. It has something to do with "not enough space" to show the menu. It happens straight when I click on the menu. When there is not enough space to drop down it shows the tendency to scroll everything up and then centers the menu.

**Comment by macedonga** [comment]
Do you still have that issue?

**Comment by svenborgmann** [comment]
I don't have access to that machine so I can't tell. If I have access and I have still that problem I reopen that issue.
