### ISSUE TITLE
Show more than 50 friends in the profile page

### ISSUE THREAD

**Issue by svenborgmann** [macedonga/beunblurred#61]
**Is your feature request related to a problem? Please describe.**
I put that in the feature request although it also could count as bug. When showing the profile it says f.e. 83 friends but it only shows 50 friends. The json also contains only 50 friends but there is also a "next" which should point to the rest (don't know how much friends are possible)

**Describe the solution you'd like**
Show more than 50 friend

**Comment by macedonga** [comment]
Fixed with latest commit

**Comment by GWPvGWP** [comment]
Fails to load the page when >200 friends...
It also seems to force a log out shortly after, but I'm not sure if that's a real correlation
