### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by ModNotNeeded** [macedonga/beunblurred#62]
Still an error type 500 online for +33 numbers (🇫🇷)

**Comment by GWPvGWP** [comment]
Not only French numbers....

**Comment by JoLukas** [comment]
The same problem for German numbers

**Comment by sveaalessxa** [comment]
It doesn’t work with german numbers…
will it ever work again?

**Comment by DrCrazy27** [comment]
> It doesn’t work with german numbers… will it ever work again?

Issue has been addressed and solved here:

https://github.com/macedonga/beunblurred/issues/65

**Comment by macedonga** [comment]
> Issue has been addressed and solved here:

It hasn't. It will only work on your local computer, not online.

**Comment by DrCrazy27** [comment]
> > Issue has been addressed and solved here:
> 
> It hasn't. It will only work on your local computer, not online.

Yeah you're right, but still it is a working solution isn't it?

**Comment by macedonga** [comment]
> Yeah you're right, but still it is a working solution isn't it?

Not for users of the website though

**Comment by DrCrazy27** [comment]
> > Yeah you're right, but still it is a working solution isn't it?
> 
> Not for users of the website though

Speaking of this, may I ask what the current problem is and why it isn't possible to just use the older version on the website or has this version it's own set of problems?

**Comment by macedonga** [comment]
> Speaking of this, may I ask what the current problem is and why it isn't possible to just use the older version on the website or has this version it's own set of problems?

The arkose labs challenge sends the domain being used to the api, and bereal blocked the beunblurred.co domain (including every subdomain) from being used. localhost will never be blocked since it is used by bereal devs (probably). The BeReal application sends a domain that is equal to "file://", so i'd have to find a way to do that. I also tried putting the challenge in an iframe that contains a url with the html in a base64 encoded url, making the domain being sent to the arkose labs api equal to `null`, but after a while that got blocked too.

**Comment by DrCrazy27** [comment]
> > Speaking of this, may I ask what the current problem is and why it isn't possible to just use the older version on the website or has this version it's own set of problems?
> 
> The arkose labs challenge sends the domain being used to the api, and bereal blocked the beunblurred.co domain (including every subdomain) from being used. localhost will never be blocked since it is used by bereal devs (probably). The BeReal application sends a domain that is equal to "file://", so i'd have to find a way to do that. I also tried putting the challenge in an iframe that contains a url with the html in a base64 encoded url, making the domain being sent to the arkose labs api equal to `null`, but after a while that got blocked too.

Oh I see. The only solution that comes to my mind rn is to just forget the website and turn the project into a software, which turns the user into it's own host and opens a tab with the correct local host address.

Alternativly I think it would be possible to use the website as a sort of window which is connected to one of various domains, that change dynamically after each session. I am no expert in this topic and I am not sure if this is managable to do. 

Either way I appreciate your work and wish you best of luck.

**Comment by Ein-Tim** [comment]
@macedonga Love it, have fun and no pressure to publish anything. You're doing all this in your spare time :)

Publishing the .IPA is enough, using AltStore (PAL) or Sidestore enables users to install apps on iPhone that are not in the App Store.

**Comment by starwarsman981** [comment]
> > Issue has been addressed and solved here:
> 
> It hasn't. It will only work on your local computer, not online.

Is there any way to get archiver to work locally?

**Comment by starwarsman981** [comment]
> > > Issue has been addressed and solved here:
> > 
> > 
> > It hasn't. It will only work on your local computer, not online.
> 
> Is there any way to get archiver to work locally?

Not an actual answer to this, but I didn't know before now that if you lose your session on beunblurred, you can get a token locally and then paste it all on there and it'll work.

**Comment by sveaalessxa** [comment]
> > > > Issue has been addressed and solved here:
> > > 
> > > 
> > > It hasn't. It will only work on your local computer, not online.
> > 
> > 
> > Is there any way to get archiver to work locally?
> 
> Not an actual answer to this, but I didn't know before now that if you lose your session on beunblurred, you can get a token locally and then paste it all on there and it'll work.

how to get a token locally?

**Comment by starwarsman981** [comment]
> > > > > Issue has been addressed and solved here:
> > > > 
> > > > 
> > > > It hasn't. It will only work on your local computer, not online.
> > > 
> > > 
> > > Is there any way to get archiver to work locally?
> > 
> > 
> > Not an actual answer to this, but I didn't know before now that if you lose your session on beunblurred, you can get a token locally and then paste it all on there and it'll work.
> 
> how to get a token locally?

Have to run beunblurred locally and sign in and get everything working. Then you can copy cookies over to the site with archiver which should work for weeks usually. Then repeat when it times out.

**Comment by sveaalessxa** [comment]
> out.

thank you! I‘m not good at that kind of stuff. could you maybe explain it again or take screenshots if possible? 
Kind regards

**Comment by davideakc** [comment]
I tried this on my localhost, I always get this error:
![error](https://github.com/user-attachments/assets/d3939412-daff-4b7d-b053-b8daa9459d4f)

**Comment by davideakc** [comment]
Sorry, I forgot to mention that this error is when I try to get the OTP code to my number. I complete the captcha and on the console it says that error. On localhost site, I get the same error that I get on https://www.beunblurred.co/.
I've Python installed, the project is working on my locahost, except for login.

**Comment by GWPvGWP** [comment]
You should not use the latest version. I presume you're doing that. Also read #65

**Comment by davideakc** [comment]
> You should not use the latest version. I presume you're doing that. Also read #65

It works, thank you!

**Comment by macedonga** [comment]
(i mean it works on beunblurred.co)

**Comment by macedonga** [comment]
Since it appears that it is still working, I will close this issue for now (hopefully, I don't jinx it)
