### ISSUE TITLE
"Download main image" and "Download secondary image" do not work as expected

### ISSUE THREAD

**Issue by svenborgmann** [macedonga/beunblurred#63]
**Describe the bug**
If there are more than one post of a friend it always downloads the latest (first) picture of main and secondary, not the second, ...

**To Reproduce**
1. Go to a post where there are more posts.
2. Click on "Download main", it downloads the first picture (the same you see)
3. Click on the right arrow to go to the next picture. Download again and you get the same image again, not the one you are seeing

**Expected behavior**
It should download the main that is shown. You can't download the second picture right now.

**Additional context**
I checked this locally and on beunblurred.co, it is still the same.
I think it was introduced when sliding was implemented?
In theory it could happen you download the second picture when you watch and download the third, don't have a case for that.

**Comment by svenborgmann** [comment]
@macedonga 
Can you please take a look at that? Right now one can not use the main branch if you want to download all the pictures ...

**Comment by macedonga** [comment]
Fixed
