### ISSUE TITLE
Still 500 error

### ISSUE THREAD

**Issue by DrCrazy27** [macedonga/beunblurred#65]
Just wanted to ask if there has been anything new regarding beunblurred. As like the past weeks many phone numbers outside the US including +49 (German) and +43 (Austria) have stopped working. I have seen that it worked again for a short amount of time but the last message was like 2 weeks ago. Has anyone found a workaround and is it currently working  or is it still broken.

**Comment by GWPvGWP** [comment]
It seems the authentication in the versions before the current last one still work. I don't know what has changed, but it might work when that is rolled back.

**Comment by DrCrazy27** [comment]
> It seems the authentication in the versions before the current last one still work. I don't know what has changed, but it might work when that is rolled back.

Do you perchance have the zib file for the previous version or is there any other way to get this version?

**Comment by GWPvGWP** [comment]
You can download older versions by looking at the commits and browse to whatever point in time you want.

**Comment by darrko54** [comment]
> You can download older versions by looking at the commits and browse to whatever point in time you want.

what commit should I download ?

**Comment by GWPvGWP** [comment]
The one before 28-10 should work if I remember correctly

**Comment by DrCrazy27** [comment]
> The one before 28-10 should work if I remember correctly

@darrko54 
GWPvGWP is right it's working.

https://github.com/macedonga/beunblurred/tree/2a3620c00c94e969e1913f8165b9851ce1287e10
Go here and download it. Then open CMD or powershell and just go to the path where you downloaded it via cd "D:\yourpath", type npm install and ignore the warning. After that create at the file destination a .env.local file with the following content:
NEXT_PUBLIC_NO_ARCHIVER=1
type  "npm run build" 
type "npm start" 
open your browser and type in http://localhost:3290/
Type in your number and do the captcha.
Then you will receive your verification code. 
 Don't wonder if you don't get an SMS, because you will probably get the code on Whatsapp.

**Comment by darrko54** [comment]
big thanks man

**Comment by mast-and** [comment]
Thanks @DrCrazy27 it actually works.
I can only see posts from 10 friends when I actually have about 30 friends who have posted. Any idea how to solve this?

**Comment by GWPvGWP** [comment]
Yeah, so that's the trick. You use the old version for authentication and then run the most recent version. So you kill the task, run the latest version, while the browser is still logged in. If you don't know how you can ask ChatGPT for example how to kill a task at your port (3290).

**Comment by mast-and** [comment]
Thank you @GWPvGWP.
I use VsCode to deploy it for the moment as I only consult it once a day to keep up to date, later on I will set up a docker.
Locally, using the two folders (auth from 20/10 and main) is enough, when you have done the login in a terminal using the old branch, you can stop it and start the main (same port with no errors).
I leave this in case someone else finds it useful.
