### ISSUE TITLE
Get rid of Telemetry (+GDPR)

### ISSUE THREAD

**Issue by Smart123s** [macedonga/beunblurred#67]
uBlock Origin is really mad at your site. I genuinely don't understand why you need so much tracking for an open source project. Are you looking to sell my phone number? Or my friends data? At least have an easy option to disable it from the self hosted version. I don't want my own server to send my information to someone else.

# Or at least have a notice about the tracing.

Btw, are you compliant with EU's GDPR? I'm pretty sure I didn't get asked before you started tracking me. You could get in a lot of trouble, especially if you accept payments.

![image](https://github.com/user-attachments/assets/e6dce68a-2432-4c9d-89a5-c81a40dda15e)

**Comment by macedonga** [comment]
> uBlock Origin is really mad at your site. I genuinely don't understand why you need so much tracking for an open source project. Are you looking to sell my phone number? Or my friends data? At least have an easy option to disable it from the self hosted version. I don't want my own server to send my information to someone else.

If you looked at the code you could see that there is actually no tracking, except Sentry, if you consider it tracking, which is for error reporting. Google Analytics and the rest is being injected by Cloudflare Zaraz, which does show a GDPR compliant consent management popup.

If you don't feel comfortable using third party services, use the official bereal application.

**Comment by Smart123s** [comment]
Thanks for the fast response. Pretty understandable. And nowadays the official BeReal app has more tracking than your site :D
Regardless, I still think that adding something similar to your comment above (about only collecting error logs) would be really good for transparency. There are just so many "BeReal Mod Sites" that try to sell your soul. I took a look at your code, and there's nothing like that going on here. I just think that users would feel a lot safer if they'd know why uBlock is showing so many blocked requests.
Thanks for your awesome work 🚀

**Comment by macedonga** [comment]
I will add a disclaimer about collecting error logs once I manage to actually get the site to work for most users, since now the captcha seems to work for only a few random people :-)
