### ISSUE TITLE
Suggestions for minor improvements

### ISSUE THREAD

**Issue by GWPvGWP** [macedonga/beunblurred#7]
Hi, 
a few suggestions from my side.

-is it possible to make posts from a single user (bonus bereals) swipeable, so from left to right and vice versa? Would be easier than clicking the arrow each time.
-I prefer to save the url of the original .webp, would it be possible to make that url accessible? The most perfect option imo would be to make it an option under the save options. Something like 'copy to clipboard'.

Would be nice to see this integrated, but as I said, it is only of minor importance

**Comment by macedonga** [comment]
It should be doable. I'll close this issue once I implemented those features :-)

**Comment by macedonga** [comment]
I've added the buttons to copy the image links on the post options. The swiping of the images is a bit more difficult than I thought, but it shouldn't take much more to finish.

**Comment by GWPvGWP** [comment]
Wow, you're so fast. Unfortunately the copying to the clipboard didn't work for me although a notification pops up saying it is copied to clipboard. Maybe the mobile browsers prevent the access to the clipboard. I haven't checked on desktop. 

I saw the swiping on instagram, so it must be possible, but my understanding of coding is too little to know how.
