### ISSUE TITLE
Installation on MacOS Terminal

### ISSUE THREAD

**Issue by JoLukas** [macedonga/beunblurred#71]
Hey, I'm not really good with the terminal in MacOS. I've already tried to generate more detailed instructions with ChatGPT, but unfortunately in vain. Can someone perhaps provide more detailed instructions for local installation for us "beginners" ;-) ? I hope someone can do this.

**Comment by macedonga** [comment]
I'll make a video tutorial for mac soon

**Comment by macedonga** [comment]
Here: https://youtu.be/Ts99LVkGs8A
