### ISSUE TITLE
error 500 

### ISSUE THREAD

**Issue by n7icoo** [macedonga/beunblurred#74]
I just tried with the website, it says a week ago that it was working but I just tried any theres still error 500. Is there any video tutorial on how to run it locally? 

Thanks

**Comment by macedonga** [comment]
That's weird, it still works for me...
I'll make a video tutorial in the next days.

**Comment by Ein-Tim** [comment]
Also works for me using a German phone number

**Comment by macedonga** [comment]
This Is the tutorial for Windows: https://youtu.be/slVedW8bT9I
